export const base = {
  // Base Colors
  'focusBorder': '#ffffff1f',
  'foreground': '#7f7f7f',
  'disabledForeground': '#6c6c6c',
  'widget.shadow': '#00000033',
  'selection.background': '#363636',
  'sash.hoverBorder': '#505050',
  // Text colors
  'textCodeBlock.background': '#292929',
  'textLink.activeForeground': '#ff8787',
  'textLink.foreground': '#ff8787cc',
  // Action colors
  'toolbar.hoverBackground': '#292929',
  // Button control
  'button.background': '#ff87877f',
  'button.hoverBackground': '#ff8787aa',
  // Dropdown control
  'dropdown.background': '#050505',
  'dropdown.border': '#ffffff3a',
  // Input control
  'input.background': '#ffffff07',
  'input.border': '#ffffff07',
  'inputOption.activeBackground': '#292929',
  'inputOption.activeForeground': '#ffffff',
  'inputOption.activeBorder': '#6c6c6c',
  // Scrollbar control
  'scrollbar.shadow': '#050505',
  'scrollbarSlider.activeBackground': '#ffffff37',
  'scrollbarSlider.background': '#ffffff17',
  'scrollbarSlider.hoverBackground': '#ffffff27',
  // Badge
  'badge.background': '#ffffff17',
  'badge.foreground': '#aaaaaa',
  // Progress bar
  'progressBar.background': '#dddddd',
  // List and trees
  'list.activeSelectionBackground': '#0f0f0f',
  'list.dropBackground': '#ffffff10',
  'list.focusBackground': '#ffffff10',
  'list.focusHighlightForeground': '#66b395',
  'list.focusOutline': '#ffffff1f',
  'list.highlightForeground': '#66b395',
  'list.hoverBackground': '#0f0f0f',
  'list.inactiveSelectionBackground': '#0f0f0f',
  'list.filterMatchBackground': '#66b39530',
  'list.filterMatchBorder': '#66b395',
  // Activity Bar
  'activityBar.background': '#050505',
  'activityBar.foreground': '#aaaaaa',
  'activityBar.border': '#ffffff15',
  'activityBarBadge.foreground': '#222222',
  'activityBarBadge.background': '#999999',
  'activityBar.activeBorder': '#aaaaaa',
  // Side bar
  'sideBar.background': '#050505',
  'sideBar.border': '#ffffff15',
  'sideBarSectionHeader.background': '#050505',
  'sideBarSectionHeader.border': '#ffffff15',
  // Minimap
  'minimap.findMatchHighlight': '#66b3959f',
  'minimap.selectionHighlight': '#7098d49f',
  'minimap.errorHighlight': '#ff8787',
  'minimap.background': '#111111',
  'minimapSlider.background': '#ffffff17',
  'minimapSlider.hoverBackground': '#ffffff27',
  'minimapSlider.activeBackground': '#ffffff37',
  // Editor Groups & Tabs
  'editorGroupHeader.tabsBackground': '#050505',
  'editorGroupHeader.tabsBorder': '#ffffff15',
  'tab.activeBackground': '#0d0d0d',
  'tab.activeBorder': '#aaaaaa',
  'tab.inactiveBackground': '#050505',
  'tab.border': '#ffffff10',
  // Editor colors
  'editor.background': '#0d0d0d',
  'editor.foreground': '#dddddd',
  'editorLineNumber.foreground': '#555555',
  'editorLineNumber.activeForeground': '#cccccc',
  'editorCursor.foreground': '#ff8787',
  'editor.selectionBackground': '#ffffff1f',
  'editor.selectionHighlightBorder': '#ffffff3f',
  'editor.wordHighlightBackground': '#ffffff1f',
  'editor.wordHighlightStrongBackground': '#ffffff1f',
  'editor.findMatchBackground': '#66b3954f',
  'editor.findMatchHighlightBackground': '#66b3952f',
  'editor.findMatchHighlightBorder': '#66b3955f',
  'editor.findMatchBorder': '#66b395',
  'searchEditor.findMatchBorder': '#66b395',
  'editor.hoverHighlightBackground': '#ffffff0f',
  'editor.lineHighlightBackground': '#212121',
  'editorLink.activeForeground': '#ff8787',
  'editorWhitespace.foreground': '#ffffff15',
  'editorIndentGuide.background': '#ffffff15',
  'editorIndentGuide.activeBackground': '#ffffff3f',
  'editorInlayHint.background': '#ffffff10',
  'editorInlayHint.foreground': '#ffffff6f',
  /// Codelens
  'editorCodeLens.foreground': '#555555',
  /// Bracket pair colorization
  'editorBracketHighlight.foreground1': '#aaaaaa7f',
  'editorBracketHighlight.foreground2': '#9999997f',
  'editorBracketHighlight.foreground3': '#8888887f',
  'editorBracketHighlight.foreground4': '#9999997f',
  /// Errors and warnings
  'editorError.foreground': '#ff8787',
  'editorWarning.foreground': '#e7d38f',
  'editorInfo.foreground': '#7098d4',
  /// The gutter contains the glyph margins and the line numbers
  'editorGutter.modifiedBackground': '#7098d47f',
  'editorGutter.addedBackground': '#66b3954f',
  'editorGutter.deletedBackground': '#ff87877f',
  // Diff editor colors
  'diffEditor.insertedTextBackground': '#66b39530',
  'diffEditor.removedTextBackground': '#ff878730',
  'diffEditor.border': '#ffffff15',
  'diffEditor.diagonalFill': '#ffffff15',
  'diffEditor.insertedLineBackground': '#66b39530',
  'diffEditor.removedLineBackground': '#ff878730',
  // Editor widget colors
  'editorWidget.background': '#181818',
  'editorSuggestWidget.background': '#0a0a0a',
  'editorSuggestWidget.selectedBackground': '#292929',
  'editorStickyScrollHover.background': '#292929',
  // Peek view colors
  'peekView.border': '#444444',
  'peekViewEditor.background': '#292929',
  'peekViewEditor.matchHighlightBackground': '#66b3953f',
  'peekViewEditor.matchHighlightBorder': '#66b395',
  'peekViewResult.matchHighlightBackground': '#66b3953f',
  'peekViewResult.selectionBackground': '#66b3953f',
  'peekViewResult.background': '#242424',
  'peekViewTitle.background': '#292929',
  'peekViewEditorStickScroll.background': '#292929',
  // Merge conflicts colors
  'merge.currentHeaderBackground': '#66b3957f',
  'merge.currentContentBackground': '#66b3953f',
  'merge.incomingHeaderBackground': '#7098d47f',
  'merge.incomingContentBackground': '#7098d43f',
  // Panel colors
  'panel.background': '#050505',
  // Status bar colors
  'statusBar.background': '#050505',
  'statusBar.foreground': '#777777',
  'statusBar.border': '#ffffff15',
  'statusBar.debuggingBackground': '#66b395',
  'statusBar.debuggingForeground': '#000000',
  'statusBar.noFolderBackground': '#0d0d0d',
  'statusBar.noFolderForeground': '#777777',
  'statusBar.focusBorder': '#00000000',
  'statusBarItem.prominentBackground': '#66b395',
  'statusBarItem.prominentForeground': '#000000',
  'statusBarItem.remoteBackground': '#66b395',
  'statusBarItem.remoteForeground': '#000000',
  'statusBarItem.errorBackground': '#ff8787',
  'statusBarItem.errorForeground': '#000000',
  'statusBarItem.warningBackground': '#d8b544',
  'statusBarItem.warningForeground': '#000000',
  // Title bar colors
  'titleBar.activeBackground': '#050505',
  'titleBar.inactiveBackground': '#0d0d0d',
  'titleBar.border': '#ffffff10',
  // Menu bar colors
  'menu.foreground': '#bbbbbb',
  'menu.background': '#050505',
  'menu.separatorBackground': '#ffffff15',
  // Command Center colors
  'commandCenter.activeBackground': '#ffffff10',
  'commandCenter.border': '#ffffff2a',
  // Banner colors
  'banner.foreground': '#dddddd',
  'banner.background': '#292929',
  // Quick picker colors
  'pickerGroup.foreground': '#66b395',
  'quickInput.background': '#050505',
  // Integrated Terminal colors
  'terminal.background': '#050505',
  'terminal.foreground': '#707080',
  'terminal.ansiBlack': '#292929',
  'terminal.ansiBlue': '#7789a3',
  'terminal.ansiBrightBlack': '#393939',
  'terminal.ansiBrightBlue': '#8799b3',
  'terminal.ansiBrightCyan': '#799a9e',
  'terminal.ansiBrightGreen': '#95a8a1',
  'terminal.ansiBrightMagenta': '#9e8aa3',
  'terminal.ansiBrightRed': '#bd9696',
  'terminal.ansiBrightWhite': '#bdbdbd',
  'terminal.ansiBrightYellow': '#c3ba9f',
  'terminal.ansiCyan': '#698a8e',
  'terminal.ansiGreen': '#859891',
  'terminal.ansiMagenta': '#8e7a93',
  'terminal.ansiRed': '#ad8686',
  'terminal.ansiWhite': '#adadad',
  'terminal.ansiYellow': '#b3aa8f',
  'terminal.selectionBackground': '#292929',
  'terminal.tab.activeBorder': '#aaaaaa',
  // Git colors
  'gitDecoration.addedResourceForeground': '#66b395',
  'gitDecoration.modifiedResourceForeground': '#e7d38f',
  'gitDecoration.deletedResourceForeground': '#ff8787',
  'gitDecoration.renamedResourceForeground': '#6ab8c0',
  'gitDecoration.ignoredResourceForeground': '#ffffff3f',
  'gitDecoration.conflictingResourceForeground': '#dd9a6a',
  // Breadcrumbs colors
  'breadcrumb.foreground': '#666666',
}
