/**
 * Default file icon associations
 * Keys are icon file basenames
 */
const fileIcons: Record<string, {
  languageIds?: Array<string>
  fileExtensions?: Array<string>
  fileNames?: Array<string>
}> = {
  'android': {
    fileNames: ['androidmanifest.xml'],
    fileExtensions: [
      'apk',
      'smali',
      'dex',
    ],
  },
  'archive': {
    fileExtensions: [
      '7z',
      'zip',
      'gz',
      'rar',
      'bz2',
      'cab',
      'iso',
      'tar',
      'xz',
    ],
  },
  'astro': {
    fileExtensions: ['astro'],
    languageIds: ['astro'],
  },
  'astro-config': {
    fileNames: [
      'astro.config.js',
      'astro.config.mjs',
      'astro.config.cjs',
      'astro.config.ts',
      'astro.config.cts',
      'astro.config.mts',
    ],
  },
  'audio': {
    fileExtensions: [
      'aac',
      'aiff',
      'alac',
      'flac',
      'm4a',
      'm4p',
      'mogg',
      'mp3',
      'oga',
      'opus',
      'wav',
      'wma',
      'wv',

      'webm',
      'mkv',
      'flv',
      'vob',
      'ogv',
      'ogg',
      'gifv',
      'avi',
      'mov',
      'qt',
      'wmv',
      'yuv',
      'rm',
      'rmvb',
      'mp4',
      'm4v',
      'mpg',
      'mp2',
      'mpeg',
      'mpe',
      'mpv',
      'm2v',
    ],
  },
  'binary': {
    languageIds: ['code-text-binary'],
    fileExtensions: ['bin'],
  },
  'c': {
    languageIds: ['c'],
    fileExtensions: [
      'c',
      'i',
      'mi',
    ],
  },
  'c-header': {
    fileExtensions: ['h'],
  },
  'caddy': {
    fileExtensions: ['caddyfile'],
    fileNames: ['caddyfile'],
  },
  'cargo': {
    fileNames: ['cargo.toml'],
  },
  'cargo-lock': {
    fileNames: ['cargo.lock'],
  },
  'clojure': {
    languageIds: ['clojure'],
    fileExtensions: [
      'clj',
      'cljs',
      'cljc',
    ],
  },
  'cmake': {
    fileExtensions: ['cmake'],
    fileNames: [
      'cmakelists.txt',
      'cmakecache.txt',
    ],
  },
  'cobol': {
    languageIds: ['cobol'],
    fileExtensions: [
      'cob',
      'cbl',
    ],
  },
  'coffeescript': {
    languageIds: ['coffeescript'],
    fileExtensions: [
      'coffee',
      'cson',
      'iced',
    ],
  },
  'cpp': {
    languageIds: ['cpp'],
    fileExtensions: [
      'cc',
      'cpp',
      'cxx',
      'c++',
      'cp',
      'mii',
      'ii',
    ],
  },
  'csharp': {
    languageIds: ['csharp'],
    fileExtensions: [
      'cs',
      'csx',
      'csharp',
    ],
  },
  'css': {
    languageIds: ['css'],
    fileExtensions: ['css'],
  },
  'csv': {
    languageIds: [
      'csv',
      'tsv',
      'psv',
    ],
    fileExtensions: [
      'csv',
      'tsv',
      'psv',
    ],
  },
  'cucumber': {
    languageIds: ['cucumber'],
    fileExtensions: [
      'feature',
      'features',
    ],
  },
  'cuda': {
    languageIds: ['cuda-cpp'],
    fileExtensions: [
      'cu',
      'cuh',
    ],
  },
  'cypress': {
    fileNames: [
      'cypress.json',
      'cypress.env.json',
      'cypress.config.ts',
      'cypress.config.js',
      'cypress.config.cjs',
      'cypress.config.mjs',
    ],
  },
  'dart': {
    languageIds: ['dart'],
    fileExtensions: ['dart'],
  },
  'dart-generated': {
    fileExtensions: [
      'freezed.dart',
      'g.dart',
    ],
  },
  'database': {
    languageIds: ['sql'],
    fileExtensions: [
      'pdb',
      'sql',
      'pks',
      'pkb',
      'accdb',
      'mdb',
      'sqlite',
      'sqlite3',
      'pgsql',
      'postgres',
      'plpgsql',
      'psql',
      'db',
      'db3',
    ],
  },
  'deno': {
    fileNames: [
      'deno.json',
      'deno.jsonc',
    ],
  },
  'dependabot': {
    fileNames: [
      'dependabot.yml',
      'dependabot.yaml',
    ],
  },
  'dhall': {
    languageIds: ['dhall'],
    fileExtensions: [
      'dhall',
      'dhallb',
    ],
  },
  'django': {
    languageIds: [
      'django-html',
      'django-txt',
    ],
    fileExtensions: ['djt'],
  },
  'docker': {
    fileExtensions: [
      'dockerfile',
      'containerfile',
    ],
    fileNames: [
      'dockerfile',
      'dockerfile.prod',
      'dockerfile.production',
      'dockerfile.alpha',
      'dockerfile.beta',
      'dockerfile.stage',
      'dockerfile.staging',
      'dockerfile.dev',
      'dockerfile.development',
      'dockerfile.local',
      'dockerfile.test',
      'dockerfile.testing',
      'dockerfile.ci',
      'dockerfile.web',
      'dockerfile.worker',

      'containerfile',
      'containerfile.prod',
      'containerfile.production',
      'containerfile.alpha',
      'containerfile.beta',
      'containerfile.stage',
      'containerfile.staging',
      'containerfile.dev',
      'containerfile.development',
      'containerfile.local',
      'containerfile.test',
      'containerfile.testing',
      'containerfile.ci',
      'containerfile.web',
      'containerfile.worker',
    ],
  },
  'docker-compose': {
    fileExtensions: [
      'docker-compose.yml',
      'docker-compose.yaml',

      'compose.yaml',
      'compose.yml',
    ],
    fileNames: [
      'docker-compose.yml',
      'docker-compose.override.yml',
      'docker-compose.prod.yml',
      'docker-compose.production.yml',
      'docker-compose.alpha.yml',
      'docker-compose.beta.yml',
      'docker-compose.stage.yml',
      'docker-compose.staging.yml',
      'docker-compose.dev.yml',
      'docker-compose.development.yml',
      'docker-compose.local.yml',
      'docker-compose.test.yml',
      'docker-compose.testing.yml',
      'docker-compose.ci.yml',
      'docker-compose.web.yml',
      'docker-compose.worker.yml',

      'docker-compose.yaml',
      'docker-compose.override.yaml',
      'docker-compose.prod.yaml',
      'docker-compose.production.yaml',
      'docker-compose.alpha.yaml',
      'docker-compose.beta.yaml',
      'docker-compose.stage.yaml',
      'docker-compose.staging.yaml',
      'docker-compose.dev.yaml',
      'docker-compose.development.yaml',
      'docker-compose.local.yaml',
      'docker-compose.test.yaml',
      'docker-compose.testing.yaml',
      'docker-compose.ci.yaml',
      'docker-compose.web.yaml',
      'docker-compose.worker.yaml',

      'compose.yaml',
      'compose.override.yaml',
      'compose.prod.yaml',
      'compose.production.yaml',
      'compose.alpha.yaml',
      'compose.beta.yaml',
      'compose.stage.yaml',
      'compose.staging.yaml',
      'compose.dev.yaml',
      'compose.development.yaml',
      'compose.local.yaml',
      'compose.test.yaml',
      'compose.testing.yaml',
      'compose.ci.yaml',
      'compose.web.yaml',
      'compose.worker.yaml',

      'compose.yml',
      'compose.override.yml',
      'compose.prod.yml',
      'compose.production.yml',
      'compose.alpha.yml',
      'compose.beta.yml',
      'compose.stage.yml',
      'compose.staging.yml',
      'compose.dev.yml',
      'compose.development.yml',
      'compose.local.yml',
      'compose.test.yml',
      'compose.testing.yml',
      'compose.ci.yml',
      'compose.web.yml',
      'compose.worker.yml',
    ],
  },
  'editorconfig': {
    languageIds: ['editorconfig'],
    fileNames: [
      '.editorconfig',
    ],
  },
  'elixir': {
    languageIds: ['elixir'],
    fileExtensions: [
      'ex',
      'exs',
      'eex',
      'leex',
      'heex',
    ],
  },
  'elm': {
    languageIds: ['elm'],
    fileExtensions: ['elm'],
  },
  'erlang': {
    languageIds: ['erlang'],
    fileExtensions: ['erl'],
  },
  'esbuild': {
    fileNames: [
      'esbuild.js',
      'esbuild.ts',
      'esbuild.cjs',
      'esbuild.mjs',
      'esbuild.config.js',
      'esbuild.config.ts',
      'esbuild.config.cjs',
      'esbuild.config.mjs',
    ],
  },
  'eslint': {
    fileNames: [
      '.eslintrc.js',
      '.eslintrc.cjs',
      '.eslintrc.yaml',
      '.eslintrc.yml',
      '.eslintrc.json',
      '.eslintrc-md.js',
      '.eslintrc-jsdoc.js',
      '.eslintrc',

      'eslint.config.js',
      'eslint.config.cjs',
      'eslint.config.mjs',
      'eslint.config.ts',
    ],
  },
  'firebase': {
    fileNames: [
      'firebase.json',
      'firestore.rules',
      'firestore.indexes.json',
      '.firebaserc',
    ],
  },
  'font': {
    fileExtensions: [
      'woff',
      'woff2',
      'ttf',
      'eot',
      'suit',
      'otf',
      'bmap',
      'fnt',
      'odttf',
      'ttc',
      'font',
      'fonts',
      'sui',
      'ntf',
      'mrf',
    ],
  },
  'gatsby': {
    fileNames: [
      'gatsby-config.js',
      'gatsby-config.mjs',
      'gatsby-config.ts',
      'gatsby-node.js',
      'gatsby-node.mjs',
      'gatsby-node.ts',
      'gatsby-browser.js',
      'gatsby-browser.tsx',
      'gatsby-ssr.js',
      'gatsby-ssr.tsx',
    ],
  },
  'git': {
    languageIds: [
      'git',
      'git-commit',
      'git-rebase',
    ],
    fileExtensions: ['patch'],
    fileNames: [
      '.gitattributes',
      '.gitconfig',
      '.gitmodules',
      '.gitkeep',
      '.keep',

      '.commitlintrc',
      '.commitlintrc.json',
      '.commitlintrc.yaml',
      '.commitlintrc.yml',
      '.commitlintrc.js',
      '.commitlintrc.cjs',
      '.commitlintrc.mjs',
      '.commitlintrc.ts',
      '.commitlintrc.cts',
      'commitlint.config.js',
      'commitlint.config.cjs',
      'commitlint.config.mjs',
      'commitlint.config.ts',
      'commitlint.config.cts',
    ],
  },
  'gitlab': {
    fileExtensions: ['gitlab-ci.yml'],
  },
  'gitpod': {
    fileNames: ['.gitpod.yml'],
  },
  'gleam': {
    fileExtensions: ['gleam'],
    languageIds: ['gleam'],
  },
  'go': {
    languageIds: ['go'],
    fileExtensions: ['go'],
  },
  'go-mod': {
    fileNames: [
      'go.mod',
      'go.sum',
      'go.work',
      'go.work.sum',
    ],
  },
  'godot': {
    languageIds: ['gdscript'],
    fileExtensions: ['gd'],
  },
  'gradle': {
    fileExtensions: ['gradle'],
    fileNames: [
      'gradle.properties',
      'gradlew',
      'gradle-wrapper.properties',
    ],
  },
  'graphql': {
    languageIds: ['graphql'],
    fileExtensions: [
      'graphql',
      'gql',
    ],
    fileNames: [
      '.graphqlconfig',
      '.graphqlrc',
      '.graphqlrc.json',
      '.graphqlrc.js',
      '.graphqlrc.cjs',
      '.graphqlrc.ts',
      '.graphqlrc.toml',
      '.graphqlrc.yaml',
      '.graphqlrc.yml',
      'graphql.config.json',
      'graphql.config.js',
      'graphql.config.cjs',
      'graphql.config.ts',
      'graphql.config.toml',
      'graphql.config.yaml',
      'graphql.config.yml',
    ],
  },
  'groovy': {
    languageIds: ['groovy'],
    fileExtensions: ['groovy'],
  },
  'gulp': {
    fileNames: [
      'gulpfile.js',
      'gulpfile.mjs',
      'gulpfile.ts',
      'gulpfile.cts',
      'gulpfile.mts',
      'gulpfile.babel.js',
    ],
  },
  'haml': {
    languageIds: ['haml'],
    fileExtensions: ['haml'],
  },
  'handlebars': {
    languageIds: ['handlebars'],
    fileExtensions: [
      'hbs',
      'mustache',
    ],
  },
  'haskell': {
    languageIds: ['haskell'],
    fileExtensions: ['hs'],
  },
  'haxe': {
    languageIds: [
      'haxe',
      'hxml',
    ],
    fileExtensions: ['hx'],
  },
  'html': {
    languageIds: ['html'],
    fileExtensions: [
      'htm',
      'html',
      'xhtml',
      'html_vm',
      'asp',
    ],
  },
  'http': {
    fileExtensions: [
      'http',
      'rest',
    ],
    fileNames: ['CNAME'],
  },
  'ignored': {
    fileExtensions: [
      'npmignore',
      'taurignore',
      'vercelignore',
      'nowignore',
      'nuxtignore',
      'dockerignore',
      'gitignore',
      'containerignore',
      'eslintignore',
      'prettierignore',
      'vscodeignore',
      'stylelintignore',
      'stylelintcache',
    ],
  },
  'image': {
    fileExtensions: [
      'png',
      'jpeg',
      'jpg',
      'gif',
      'ico',
      'tif',
      'tiff',
      'psd',
      'psb',
      'ami',
      'apx',
      'avif',
      'bmp',
      'bpg',
      'brk',
      'cur',
      'dds',
      'dng',
      'exr',
      'fpx',
      'gbr',
      'img',
      'jbig2',
      'jb2',
      'jng',
      'jxr',
      'pgf',
      'pic',
      'raw',
      'webp',
      'eps',
      'afphoto',
      'ase',
      'aseprite',
      'clip',
      'cpt',
      'heif',
      'heic',
      'kra',
      'mdp',
      'ora',
      'pdn',
      'reb',
      'sai',
      'tga',
      'xcf',
      'jfif',
      'ppm',
      'pbm',
      'pgm',
      'pnm',
      'icns',
    ],
  },
  'ionic': {
    fileNames: [
      'ionic.config.json',
      '.io-config.json',
    ],
  },
  'java': {
    languageIds: ['java'],
    fileExtensions: [
      'java',
      'jsp',
      'class',
      'jar',
    ],
  },
  'javascript': {
    languageIds: ['javascript'],
    fileExtensions: [
      'esx',
      'js',
      'cjs',
      'mjs',
    ],
  },
  'javascript-x': {
    languageIds: ['javascriptreact'],
    fileExtensions: ['jsx'],
  },
  'json': {
    languageIds: ['hjson'],
    fileExtensions: [
      'json',
      'jsonc',
      'tsbuildinfo',
      'json5',
      'jsonl',
      'ndjson',
      'hjson',
      'webmanifest',
    ],
    fileNames: [
      '.jscsrc',
      '.jshintrc',
      'composer.lock',
      '.jsbeautifyrc',
      '.esformatter',
      'cdp.pid',
      '.lintstagedrc',
      '.whitesource',
    ],
  },
  'jupyter': {
    languageIds: ['jupyter'],
    fileExtensions: ['ipynb'],
  },
  'key': {
    fileExtensions: [
      'pub',
      'key',
      'pem',
      'asc',
      'gpg',
      'passwd',
      'keystore',
    ],
    fileNames: ['.htpasswd'],
  },
  'kotlin': {
    fileExtensions: [
      'kt',
      'kts',
    ],
  },
  'latex': {
    languageIds: [
      'tex',
      'doctex',
      'latex',
      'latex-expl3',
    ],
    fileExtensions: [
      'tex',
      'sty',
      'dtx',
      'ltx',
    ],
  },
  'lefthook': {
    fileNames: [
      'lefthook.yml',
      'lefthook.yaml',
      'lefthook.toml',
      'lefthook.json',
      '.lefthook.yml',
      '.lefthook.yaml',
      '.lefthook.toml',
      '.lefthook.json',
      '.lefthook-local.yml',
      '.lefthook-local.yaml',
      '.lefthook-local.toml',
      '.lefthook-local.json',
    ],
  },
  'less': {
    languageIds: ['less'],
    fileExtensions: ['less'],
  },
  'locked': {
    fileExtensions: [
      'lock',
      'lockb',
    ],
    fileNames: [
      'package-lock.json',
      'pnpm-lock.yaml',
    ],
  },
  'lisp': {
    fileExtensions: [
      'lisp',
      'lsp',
      'cl',
      'fast',
    ],
  },
  'lua': {
    languageIds: ['lua'],
    fileExtensions: ['lua', 'luau'],
    fileNames: ['.luacheckrc'],
  },
  'makefile': {
    languageIds: ['makefile'],
    fileExtensions: ['mk'],
    fileNames: [
      'makefile',
      'gnumakefile',
      'kbuild',
    ],
  },
  'markdown': {
    languageIds: ['markdown'],
    fileExtensions: [
      'md',
      'markdown',
      'rst',
    ],
  },
  'markdown-mdx': {
    fileExtensions: ['mdx'],
  },
  'marko': {
    fileExtensions: ['marko'],
  },
  'matlab': {
    languageIds: ['matlab'],
  },
  'maven': {
    fileNames: [
      'maven.config',
      'jvm.config',
      'pom.xml',
    ],
  },
  'mermaid': {
    fileExtensions: [
      'mmd',
      'mermaid',
    ],
  },
  'meson': {
    fileNames: [
      'meson.build',
      'meson_options.txt',
    ],
    fileExtensions: ['wrap'],
  },
  'mjml': {
    fileExtensions: ['mjml'],
    fileNames: ['.mjmlconfig'],
  },
  'modernizr': {
    fileNames: [
      '.modernizrrc',
      '.modernizrrc.js',
      '.modernizrrc.json',
    ],
  },
  'nativescript': {
    fileNames: [
      'nativescript.config.ts',
      'nativescript.config.js',
    ],
  },
  'nest': {
    fileNames: [
      'nest-cli.json',
      'nestconfig.json',
      '.nest-cli.json',
      '.nestconfig.json',
    ],
  },
  'netlify': {
    fileNames: [
      'netlify.json',
      'netlify.yml',
      'netlify.yaml',
      'netlify.toml',
    ],
  },
  'next': {
    fileNames: [
      'next.config.js',
      'next.config.mjs',
      'next.config.ts',
      'next.config.mts',
    ],
  },
  'nginx': {
    fileNames: ['nginx.conf'],
    fileExtensions: [
      'nginx',
      'nginxconf',
      'nginxconfig',
    ],
  },
  'nim': {
    languageIds: [
      'nim',
      'nimble',
    ],
    fileExtensions: [
      'nim',
      'nimble',
    ],
  },
  'ninja': {
    fileExtensions: ['ninja'],
  },
  'nix': {
    languageIds: ['nix'],
    fileExtensions: ['nix'],
  },
  'nodemon': {
    fileNames: [
      'nodemon.json',
      'nodemon-debug.json',
    ],
  },
  'npm': {
    fileNames: ['.npmrc'],
  },
  'nuget': {
    fileNames: [
      'nuget.config',
      '.nuspec',
      'nuget.exe',
    ],
    fileExtensions: ['nupkg'],
  },
  'nunjucks': {
    languageIds: ['nunjucks'],
    fileExtensions: [
      'njk',
      'nunjucks',
    ],
  },
  'nuxt': {
    fileNames: [
      '.nuxtrc',
      'nuxt.config.js',
      'nuxt.config.ts',
    ],
  },
  'ocaml': {
    fileExtensions: [
      'ml',
      'mli',
      'cmx',
    ],
  },
  'org': {
    languageIds: ['org'],
    fileExtensions: ['org'],
  },
  'pandacss': {
    fileNames: [
      'panda.config.ts',
      'panda.config.js',
      'panda.config.mjs',
      'panda.config.mts',
      'panda.config.cjs',
    ],
  },
  'perl': {
    languageIds: [
      'perl',
      'perl6',
    ],
    fileExtensions: [
      'pm',
      'raku',
    ],
  },
  'php': {
    languageIds: ['php'],
    fileExtensions: ['php'],
  },
  'phrase': {
    fileNames: [
      '.phrase.yml',
      '.phraseapp.yml',
      '.phrase.yaml',
      '.phraseapp.yaml',
    ],
  },
  'playwright': {
    fileNames: [
      'playwright.config.js',
      'playwright.config.mjs',
      'playwright.config.ts',
    ],
  },
  'package': {
    fileNames: [
      'package.json',
      'pnpm-workspace.yml',
      'pnpm-workspace.yaml',
    ],
  },
  'postcss': {
    languageIds: ['postcss'],
    fileExtensions: [
      'pcss',
      'sss',
    ],
  },
  'postcss-config': {
    fileNames: [
      'postcss.config.js',
      'postcss.config.cjs',
      'postcss.config.ts',
      'postcss.config.cts',
      '.postcssrc.js',
      '.postcssrc.cjs',
      '.postcssrc.ts',
      '.postcssrc.cts',
      '.postcssrc',
      '.postcssrc.json',
      '.postcssrc.yaml',
      '.postcssrc.yml',
    ],
  },
  'prettier': {
    fileNames: [
      'prettier.config.js',
      'prettier.config.cjs',
      'prettier.config.mjs',
      '.prettierrc',
      '.prettierrc.js',
      '.prettierrc.cjs',
      '.prettierrc.mjs',
      '.prettierrc.json',
      '.prettierrc.json5',
      '.prettierrc.yaml',
      '.prettierrc.yml',
      '.prettierrc.toml',
    ],
  },
  'prisma': {
    fileNames: ['prisma.yml'],
    fileExtensions: ['prisma'],
  },
  'prolog': {
    languageIds: ['prolog'],
    fileExtensions: [
      'p',
      'pro',
      'pl',
    ],
  },
  'properties': {
    languageIds: [
      'ini',
      'properties',
      'spring-boot-properties',
    ],
    fileExtensions: [
      'ini',
      'dlc',
      'config',
      'conf',
      'properties',
      'prop',
      'settings',
      'option',
      'props',
      'prefs',
      'sln.dotsettings',
      'sln.dotsettings.user',
      'cfg',
      'config.ts',
    ],
  },
  'protobuf': {
    languageIds: ['proto'],
    fileExtensions: ['proto'],
  },
  'pug': {
    languageIds: ['jade'],
    fileExtensions: [
      'jade',
      'pug',
    ],
    fileNames: [
      '.pug-lintrc',
      '.pug-lintrc.js',
      '.pug-lintrc.json',
    ],
  },
  'python': {
    languageIds: ['python'],
    fileExtensions: [
      'py',
      'pyc',
      'pyo',
      'pyd',
    ],
  },
  'r': {
    languageIds: [
      'r',
      'rsweave',
    ],
    fileExtensions: [
      'r',
      'rmd',
    ],
    fileNames: ['.Rhistory'],
  },
  'reason': {
    languageIds: [
      'reason',
      'reason_lisp',
    ],
    fileExtensions: [
      're',
      'rei',
    ],
  },
  'redwood': {
    fileNames: ['redwood.toml'],
  },
  'renovate': {
    fileNames: [
      '.renovaterc',
      '.renovaterc.json',
      'renovate.json',
      'renovate.json5',
      'renovate-config.json',
    ],
  },
  'rescript': {
    languageIds: ['rescript'],
    fileExtensions: ['res'],
  },
  'rollup': {
    fileNames: [
      'rollup.config.js',
      'rollup.config.mjs',
      'rollup.config.ts',
    ],
  },
  'ruby': {
    languageIds: ['ruby'],
    fileExtensions: [
      'rb',
      'rbs',
    ],
    fileNames: ['.ruby-version'],
  },
  'ruby-erb': {
    fileExtensions: ['erb'],
  },
  'ruby-gem': {
    fileNames: ['gemfile'],
  },
  'rust': {
    languageIds: ['rust'],
    fileExtensions: [
      'rs',
      'ron',
    ],
  },
  'sass': {
    languageIds: [
      'sass',
      'scss',
    ],
    fileExtensions: [
      'scss',
      'sass',
    ],
  },
  'scala': {
    languageIds: ['scala'],
    fileExtensions: [
      'scala',
      'sc',
    ],
  },
  'security': {
    fileNames: [
      'security.md',
      'security.txt',
      'security',
    ],
  },
  'sentry': {
    fileNames: ['.sentryclirc'],
  },
  'serverless': {
    fileNames: [
      'serverless.yml',
      'serverless.yaml',
      'serverless.json',
      'serverless.js',
      'serverless.ts',
    ],
  },
  'shader': {
    languageIds: [
      'hlsl',
      'glsl',
      'wgsl',
    ],
    fileExtensions: [
      'glsl',
      'vert',
      'tesc',
      'tese',
      'geom',
      'frag',
      'comp',
      'vert.glsl',
      'tesc.glsl',
      'tese.glsl',
      'geom.glsl',
      'frag.glsl',
      'comp.glsl',
      'vertex.glsl',
      'geometry.glsl',
      'fragment.glsl',
      'compute.glsl',
      'ts.glsl',
      'gs.glsl',
      'vs.glsl',
      'fs.glsl',
      'shader',
      'vertexshader',
      'fragmentshader',
      'geometryshader',
      'computeshader',
      'hlsl',
      'pixel.hlsl',
      'geometry.hlsl',
      'compute.hlsl',
      'tessellation.hlsl',
      'px.hlsl',
      'geom.hlsl',
      'comp.hlsl',
      'tess.hlsl',
      'wgsl',
    ],
  },
  'shell': {
    languageIds: [
      'awk',
      'bat',
      'shellscript',
      'powershell',
    ],
    fileExtensions: [
      'sh',
      'ksh',
      'csh',
      'tcsh',
      'zsh',
      'bash',
      'awk',
      'fish',
      'bat',
      'cmd',

      'ps1',
      'psm1',
      'psd1',
      'ps1xml',
      'psc1',
      'pssc',
    ],
    fileNames: [
      'applypatch-msg',
      'pre-applypatch',
      'post-applypatch',
      'pre-commit',
      'prepare-commit-message',
      'commit-msg',
      'post-commit',
      'pre-rebase',
      'post-checkout',
      'post-merge',
      'pre-receive',
      'update',
      'post-receive',
      'post-update',
      'pre-auto-gc',
      'post-rewrite',
      'pre-push',
    ],
  },
  'sketch': {
    fileExtensions: ['sketch'],
  },
  'snowpack': {
    fileNames: [
      'snowpack.config.js',
      'snowpack.config.cjs',
      'snowpack.config.mjs',
      'snowpack.config.ts',
      'snowpack.config.cts',
      'snowpack.config.mts',
      'snowpack.deps.json',
      'snowpack.config.json',
    ],
  },
  'solidity': {
    languageIds: ['solidity'],
    fileExtensions: ['sol'],
  },
  'sonar-cloud': {
    fileNames: [
      'sonar-project.properties',
      '.sonarcloud.properties',
      'sonarcloud.yaml',
    ],
  },
  'stencil': {
    fileNames: [
      'stencil.config.js',
      'stencil.config.ts',
    ],
  },
  'stitches': {
    fileNames: [
      'stitches.config.js',
      'stitches.config.ts',
    ],
  },
  'storybook': {
    fileExtensions: [
      'stories.js',
      'stories.jsx',
      'stories.mdx',
      'story.js',
      'story.jsx',
      'stories.ts',
      'stories.tsx',
      'story.ts',
      'story.tsx',
      'story.mdx',
    ],
  },
  'stylelint': {
    fileNames: [
      'stylelint.config.js',
      'stylelint.config.cjs',
      'stylelint.config.mjs',
      '.stylelintrc',
      '.stylelintrc.json',
      '.stylelintrc.yaml',
      '.stylelintrc.yml',
      '.stylelintrc.js',
      '.stylelintrc.cjs',
      '.stylelintrc.mjs',
    ],
  },
  'svelte': {
    languageIds: ['svelte'],
    fileExtensions: ['svelte'],
  },
  'svelte-config': {
    fileNames: [
      'svelte.config.js',
      'svelte.config.ts',
      'svelte.config.cjs',
      'svelte.config.mjs',
    ],
  },
  'svg': {
    languageIds: ['svg'],
    fileExtensions: ['svg'],
  },
  'swift': {
    languageIds: ['swift'],
    fileExtensions: ['swift'],
  },
  'tailwind': {
    fileNames: [
      'tailwind.js',
      'tailwind.ts',
      'tailwind.config.js',
      'tailwind.config.cjs',
      'tailwind.config.mjs',
      'tailwind.config.ts',
      'tailwind.config.cts',
      'tailwind.config.mts',
    ],
  },
  'tauri': {
    fileNames: [
      'tauri.conf.json',
      'tauri.config.json',
      'tauri.linux.conf.json',
      'tauri.windows.conf.json',
      'tauri.macos.conf.json',
    ],
    fileExtensions: ['tauri'],
  },
  'terraform': {
    languageIds: ['terraform'],
    fileExtensions: [
      'tf',
      'tf.json',
      'tfvars',
      'tfstate',
      'tfbackend',
    ],
  },
  'toml': {
    languageIds: ['toml'],
    fileExtensions: ['toml'],
  },
  'twig': {
    languageIds: ['twig'],
    fileExtensions: ['twig'],
  },
  'typescript': {
    languageIds: ['typescript'],
    fileExtensions: ['ts'],
  },
  'typescript-d': {
    fileExtensions: ['d.ts'],
  },
  'typescript-x': {
    languageIds: ['typescriptreact'],
    fileExtensions: ['tsx'],
  },
  'unity': {
    languageIds: ['shaderlab'],
    fileExtensions: ['unity'],
  },
  'unocss': {
    fileNames: [
      'uno.config.js',
      'uno.config.mjs',
      'uno.config.ts',
      'uno.config.mts',
      'unocss.config.js',
      'unocss.config.mjs',
      'unocss.config.ts',
      'unocss.config.mts',
    ],
  },
  'v': {
    languageIds: ['v'],
    fileExtensions: ['v'],
    fileNames: [
      'vpkg.json',
      'v.mod',
    ],
  },
  'vento': {
    fileExtensions: ['vto'],
  },
  'vercel': {
    fileNames: [
      'now.json',
      'vercel.json',
    ],
  },
  'vim': {
    languageIds: ['viml'],
    fileExtensions: [
      'vimrc',
      'gvimrc',
      'exrc',
      'vim',
      'viminfo',
    ],
  },
  'visual-studio': {
    languageIds: [
      'testOutput',
      'vb',
    ],
    fileExtensions: [
      'csproj',
      'ruleset',
      'sln',
      'suo',
      'vb',
      'vbs',
      'vcxitems',
      'vcxitems.filters',
      'vcxproj',
      'vcxproj.filters',
    ],
  },
  'vite': {
    fileNames: [
      'vite.config.js',
      'vite.config.mjs',
      'vite.config.cjs',
      'vite.config.ts',
      'vite.config.cts',
      'vite.config.mts',
    ],
  },
  'vitest': {
    fileNames: [
      'vitest.config.ts',
      'vitest.config.mts',
      'vitest.config.cts',
      'vitest.config.js',
      'vitest.config.mjs',
      'vitest.config.cjs',
    ],
  },
  'vscode': {
    fileExtensions: [
      'vsixmanifest',
      'vsix',
      'code-workplace',
      'code-workspace',
      'code-profile',
      'code-snippets',
    ],
  },
  'vue': {
    languageIds: ['vue'],
    fileExtensions: ['vue'],
  },
  'vue-config': {
    fileNames: [
      'vue.config.js',
      'vue.config.ts',
    ],
  },
  'web-assembly': {
    fileExtensions: [
      'wat',
      'wasm',
    ],
  },
  'webpack': {
    fileNames: [
      'webpack.js',
      'webpack.cjs',
      'webpack.mjs',
      'webpack.ts',
      'webpack.cts',
      'webpack.mts',
      'webpack.base.js',
      'webpack.base.cjs',
      'webpack.base.mjs',
      'webpack.base.ts',
      'webpack.base.cts',
      'webpack.base.mts',
      'webpack.config.js',
      'webpack.config.cjs',
      'webpack.config.mjs',
      'webpack.config.ts',
      'webpack.config.cts',
      'webpack.config.mts',
      'webpack.common.js',
      'webpack.common.cjs',
      'webpack.common.mjs',
      'webpack.common.ts',
      'webpack.common.cts',
      'webpack.common.mts',
      'webpack.config.common.js',
      'webpack.config.common.cjs',
      'webpack.config.common.mjs',
      'webpack.config.common.ts',
      'webpack.config.common.cts',
      'webpack.config.common.mts',
      'webpack.config.common.babel.js',
      'webpack.config.common.babel.ts',
      'webpack.dev.js',
      'webpack.dev.cjs',
      'webpack.dev.mjs',
      'webpack.dev.ts',
      'webpack.dev.cts',
      'webpack.dev.mts',
      'webpack.development.js',
      'webpack.development.cjs',
      'webpack.development.mjs',
      'webpack.development.ts',
      'webpack.development.cts',
      'webpack.development.mts',
      'webpack.config.dev.js',
      'webpack.config.dev.cjs',
      'webpack.config.dev.mjs',
      'webpack.config.dev.ts',
      'webpack.config.dev.cts',
      'webpack.config.dev.mts',
      'webpack.config.dev.babel.js',
      'webpack.config.dev.babel.ts',
      'webpack.config.main.js',
      'webpack.config.renderer.ts',
      'webpack.mix.js',
      'webpack.mix.cjs',
      'webpack.mix.mjs',
      'webpack.mix.ts',
      'webpack.mix.cts',
      'webpack.mix.mts',
      'webpack.prod.js',
      'webpack.prod.cjs',
      'webpack.prod.mjs',
      'webpack.prod.ts',
      'webpack.prod.cts',
      'webpack.prod.mts',
      'webpack.prod.config.js',
      'webpack.prod.config.cjs',
      'webpack.prod.config.mjs',
      'webpack.prod.config.ts',
      'webpack.prod.config.cts',
      'webpack.prod.config.mts',
      'webpack.production.js',
      'webpack.production.cjs',
      'webpack.production.mjs',
      'webpack.production.ts',
      'webpack.production.cts',
      'webpack.production.mts',
      'webpack.server.js',
      'webpack.server.cjs',
      'webpack.server.mjs',
      'webpack.server.ts',
      'webpack.server.cts',
      'webpack.server.mts',
      'webpack.client.js',
      'webpack.client.cjs',
      'webpack.client.mjs',
      'webpack.client.ts',
      'webpack.client.cts',
      'webpack.client.mts',
      'webpack.config.server.js',
      'webpack.config.server.cjs',
      'webpack.config.server.mjs',
      'webpack.config.server.ts',
      'webpack.config.server.cts',
      'webpack.config.server.mts',
      'webpack.config.client.js',
      'webpack.config.client.cjs',
      'webpack.config.client.mjs',
      'webpack.config.client.ts',
      'webpack.config.client.cts',
      'webpack.config.client.mts',
      'webpack.config.production.babel.js',
      'webpack.config.production.babel.ts',
      'webpack.config.prod.babel.js',
      'webpack.config.prod.babel.cjs',
      'webpack.config.prod.babel.mjs',
      'webpack.config.prod.babel.ts',
      'webpack.config.prod.babel.cts',
      'webpack.config.prod.babel.mts',
      'webpack.config.prod.js',
      'webpack.config.prod.cjs',
      'webpack.config.prod.mjs',
      'webpack.config.prod.ts',
      'webpack.config.prod.cts',
      'webpack.config.prod.mts',
      'webpack.config.production.js',
      'webpack.config.production.cjs',
      'webpack.config.production.mjs',
      'webpack.config.production.ts',
      'webpack.config.production.cts',
      'webpack.config.production.mts',
      'webpack.config.staging.js',
      'webpack.config.staging.cjs',
      'webpack.config.staging.mjs',
      'webpack.config.staging.ts',
      'webpack.config.staging.cts',
      'webpack.config.staging.mts',
      'webpack.config.babel.js',
      'webpack.config.babel.ts',
      'webpack.config.base.babel.js',
      'webpack.config.base.babel.ts',
      'webpack.config.base.js',
      'webpack.config.base.cjs',
      'webpack.config.base.mjs',
      'webpack.config.base.ts',
      'webpack.config.base.cts',
      'webpack.config.base.mts',
      'webpack.config.staging.babel.js',
      'webpack.config.staging.babel.ts',
      'webpack.config.coffee',
      'webpack.config.test.js',
      'webpack.config.test.cjs',
      'webpack.config.test.mjs',
      'webpack.config.test.ts',
      'webpack.config.test.cts',
      'webpack.config.test.mts',
      'webpack.config.vendor.js',
      'webpack.config.vendor.cjs',
      'webpack.config.vendor.mjs',
      'webpack.config.vendor.ts',
      'webpack.config.vendor.cts',
      'webpack.config.vendor.mts',
      'webpack.config.vendor.production.js',
      'webpack.config.vendor.production.cjs',
      'webpack.config.vendor.production.mjs',
      'webpack.config.vendor.production.ts',
      'webpack.config.vendor.production.cts',
      'webpack.config.vendor.production.mts',
      'webpack.test.js',
      'webpack.test.cjs',
      'webpack.test.mjs',
      'webpack.test.ts',
      'webpack.test.cts',
      'webpack.test.mts',
      'webpack.dist.js',
      'webpack.dist.cjs',
      'webpack.dist.mjs',
      'webpack.dist.ts',
      'webpack.dist.cts',
      'webpack.dist.mts',
      'webpackfile.js',
      'webpackfile.cjs',
      'webpackfile.mjs',
      'webpackfile.ts',
      'webpackfile.cts',
      'webpackfile.mts',
    ],
  },
  'wxt': {
    fileNames: [
      'wxt.config.js',
      'wxt.config.ts',
    ],
  },
  'xaml': {
    fileExtensions: ['xaml'],
  },
  'xml': {
    fileExtensions: [
      'xml',
      'plist',
      'xsd',
      'dtd',
      'xsl',
      'xslt',
      'resx',
      'iml',
      'xquery',
      'tmLanguage',
      'manifest',
      'project',
      'xml.dist',
      'xml.dist.sample',
      'dmn',
      'jrxml',
    ],
    fileNames: ['.htaccess'],
  },
  'yaml': {
    languageIds: [
      'yaml',
      'spring-boot-properties-yaml',
    ],
    fileExtensions: [
      'yml',
      'yaml',
    ],
  },
  'zig': {
    fileExtensions: ['zig'],
  },
}

const { languageIds, fileExtensions, fileNames } = Object.entries(fileIcons).reduce(
  ({ languageIds, fileExtensions, fileNames }, [name, icon]) => ({
    languageIds: {
      ...languageIds,
      ...icon.languageIds?.reduce((a, c) => ({ ...a, [c]: name }), {}),
    },
    fileExtensions: {
      ...fileExtensions,
      ...icon.fileExtensions?.reduce((a, c) => ({ ...a, [c]: name }), {}),
    },
    fileNames: {
      ...fileNames,
      ...icon.fileNames?.reduce((a, c) => ({ ...a, [c]: name }), {}),
    },
  }),
  {
    languageIds: {},
    fileExtensions: {},
    fileNames: {},
  },
)

export { fileExtensions, fileIcons, fileNames, languageIds }
