import {
  patcherBase, patcherComment,
  patcherGo,
  patcherHTML, patcherMarkdown,
  patcherRuby, patcherRust,
  patcherVue, patcherXML, patcherYAML,
} from './tokens'

export function generator({ type, name }) {
  return {
    type,
    name,
    colors: {
      // Base Colors
      'focusBorder': '#00000000',
      'foreground': '#7F7F7F',
      'disabledForeground': '#6C6C6C',
      'widget.shadow': '#00000000',
      'selection.background': '#363636',
      'sash.hoverBorder': '#505050',
      // Text colors
      'textCodeBlock.background': '#292929',
      'textLink.activeForeground': '#81D2CEEE',
      'textLink.foreground': '#81D2CECC',
      // Action colors
      'toolbar.hoverBackground': '#292929',
      // Button control
      'button.border': '#00000000',
      'button.foreground': '#000000EE',
      'button.background': '#81D2CECC',
      'button.hoverBackground': '#81D2CEEE',
      // Dropdown control
      'dropdown.background': '#050505',
      'dropdown.border': '#FFFFFF11',
      // Input control
      'input.background': '#FFFFFF07',
      'input.border': '#FFFFFF11',
      'inputOption.activeBackground': '#292929',
      'inputOption.activeForeground': '#FFFFFFDD',
      'inputOption.activeBorder': '#6C6C6C',
      // Scrollbar control
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.activeBackground': '#FFFFFF3F',
      'scrollbarSlider.background': '#FFFFFF11',
      'scrollbarSlider.hoverBackground': '#FFFFFF2F',
      // Badge
      'badge.background': '#FFFFFF11',
      'badge.foreground': '#AAAAAA',
      // Progress bar
      'progressBar.background': '#DDDDDD',
      // List and trees
      'list.activeSelectionBackground': '#0F0F0F',
      'list.dropBackground': '#FFFFFF11',
      'list.focusBackground': '#FFFFFF11',
      'list.focusHighlightForeground': '#81D2CEEE',
      'list.focusOutline': '#FFFFFF11',
      'list.highlightForeground': '#81D2CEEE',
      'list.hoverBackground': '#0F0F0F',
      'list.inactiveSelectionBackground': '#0F0F0F',
      'list.inactiveSelectionForeground': '#FFFFFFDD',
      'list.filterMatchBackground': '#81D2CE30',
      'list.filterMatchBorder': '#81D2CEEE',
      // Activity Bar
      'activityBar.background': '#050505',
      'activityBar.foreground': '#AAAAAA',
      'activityBar.border': '#FFFFFF11',
      'activityBarBadge.foreground': '#222222',
      'activityBarBadge.background': '#999999',
      'activityBar.activeBorder': '#81D2CEEE',
      // Side bar
      'sideBar.background': '#050505',
      'sideBar.border': '#FFFFFF11',
      'sideBarSectionHeader.background': '#050505',
      'sideBarSectionHeader.border': '#FFFFFF11',
      // Minimap
      'minimap.findMatchHighlight': '#81D2CE9F',
      'minimap.selectionHighlight': '#7098D49F',
      'minimap.errorHighlight': '#FF8787AA',
      'minimap.background': '#111111',
      'minimapSlider.background': '#FFFFFF11',
      'minimapSlider.hoverBackground': '#FFFFFF27',
      'minimapSlider.activeBackground': '#FFFFFF37',
      // Editor colors
      'editorOverviewRuler.border': '#00000000',
      // Editor Groups & Tabs
      'editorGroupHeader.tabsBackground': '#050505',
      'editorGroupHeader.tabsBorder': '#FFFFFF11',
      'tab.activeBackground': '#0F0F0F',
      'tab.activeBorderTop': '#81D2CEEE',
      'tab.inactiveBackground': '#050505',
      'tab.border': '#FFFFFF11',
      // Editor colors
      'editor.background': '#0D0D0D',
      'editor.foreground': '#DDDDDD',
      'editorLineNumber.foreground': '#555555',
      'editorLineNumber.activeForeground': '#CCCCCC',
      'editorCursor.foreground': '#81D2CEEE',
      'editor.selectionBackground': '#FFFFFF11',
      'editor.selectionHighlightBorder': '#FFFFFF3F',
      'editor.wordHighlightBackground': '#FFFFFF11',
      'editor.wordHighlightStrongBackground': '#FFFFFF11',
      'editor.findMatchBackground': '#81D2CE4F',
      'editor.findMatchHighlightBackground': '#81D2CE2F',
      'editor.findMatchHighlightBorder': '#81D2CE5F',
      'editor.findMatchBorder': '#81D2CEEE',
      'searchEditor.findMatchBorder': '#81D2CEEE',
      'editor.hoverHighlightBackground': '#FFFFFF11',
      'editor.lineHighlightBackground': '#212121',
      'editorLink.activeForeground': '#81D2CEEE',
      'editorWhitespace.foreground': '#FFFFFF11',
      'editorIndentGuide.background': '#FFFFFF11',
      'editorIndentGuide.activeBackground': '#FFFFFF3F',
      'editorInlayHint.background': '#FFFFFF11',
      'editorInlayHint.foreground': '#FFFFFF6F',
      /// Codelens
      'editorCodeLens.foreground': '#555555',
      /// Bracket pair colorization
      'editorBracketHighlight.foreground1': '#AAAAAA77',
      'editorBracketHighlight.foreground2': '#99999977',
      'editorBracketHighlight.foreground3': '#88888877',
      'editorBracketHighlight.foreground4': '#77777777',
      'editorBracketHighlight.foreground5': '#66666677',
      'editorBracketHighlight.foreground6': '#55555577',
      /// Errors and warnings
      'editorError.foreground': '#FF8787AA',
      'editorWarning.foreground': '#E7D38FBB',
      'editorInfo.foreground': '#7098D4',
      /// The gutter contains the glyph margins and the line numbers
      'editorGutter.modifiedBackground': '#7098D47F',
      'editorGutter.addedBackground': '#81D2CE4F',
      'editorGutter.deletedBackground': '#FF87877F',
      // Diff editor colors
      'diffEditor.insertedTextBackground': '#81D2CE30',
      'diffEditor.removedTextBackground': '#FF878730',
      'diffEditor.border': '#FFFFFF11',
      'diffEditor.diagonalFill': '#FFFFFF11',
      'diffEditor.insertedLineBackground': '#81D2CE30',
      'diffEditor.removedLineBackground': '#FF878730',
      // Editor widget colors
      'editorWidget.background': '#181818',
      'editorSuggestWidget.background': '#0A0A0A',
      'editorSuggestWidget.selectedBackground': '#292929',
      'editorHoverWidget.statusBarBackground': '#292929',
      'editorStickyScrollHover.background': '#292929',
      // Peek view colors
      'peekView.border': '#444444',
      'peekViewEditor.background': '#292929',
      'peekViewEditor.matchHighlightBackground': '#81D2CE3F',
      'peekViewEditor.matchHighlightBorder': '#81D2CEEE',
      'peekViewResult.matchHighlightBackground': '#81D2CE3F',
      'peekViewResult.selectionBackground': '#81D2CE3F',
      'peekViewResult.background': '#242424',
      'peekViewTitle.background': '#292929',
      'peekViewEditorStickScroll.background': '#292929',
      // Merge conflicts colors
      'merge.currentHeaderBackground': '#81D2CE7F',
      'merge.currentContentBackground': '#81D2CE3F',
      'merge.incomingHeaderBackground': '#7098D47F',
      'merge.incomingContentBackground': '#7098D43F',
      // Panel colors
      'panel.background': '#050505',
      'panel.border': '#FFFFFF11',
      'panelTitle.activeBorder': '#81D2CECC',
      // Status bar colors
      'statusBar.background': '#050505',
      'statusBar.foreground': '#777777',
      'statusBar.border': '#FFFFFF11',
      'statusBar.debuggingBackground': '#81D2CEEE',
      'statusBar.debuggingForeground': '#000000',
      'statusBar.noFolderBackground': '#0D0D0D',
      'statusBar.noFolderForeground': '#777777',
      'statusBar.focusBorder': '#00000000',
      'statusBarItem.prominentBackground': '#81D2CEEE',
      'statusBarItem.prominentForeground': '#000000',
      'statusBarItem.remoteBackground': '#81D2CEEE',
      'statusBarItem.remoteForeground': '#000000',
      'statusBarItem.errorBackground': '#FF8787AA',
      'statusBarItem.errorForeground': '#000000',
      'statusBarItem.warningBackground': '#D8B544AA',
      'statusBarItem.warningForeground': '#000000',
      'statusBarItem.remoteHoverForeground': '#FFFFFFDD',
      // Title bar colors
      'titleBar.activeBackground': '#050505',
      'titleBar.inactiveBackground': '#0d0d0d',
      'titleBar.border': '#FFFFFF11',
      // Menu bar colors
      'menu.foreground': '#BBBBBBDD',
      'menu.background': '#050505',
      'menu.separatorBackground': '#FFFFFF11',
      // Command Center colors
      'commandCenter.activeBackground': '#FFFFFF11',
      'commandCenter.border': '#FFFFFF11',
      // Banner colors
      'banner.foreground': '#BBBBBBDD',
      'banner.background': '#050505',
      // Quick picker colors
      'pickerGroup.foreground': '#81D2CEEE',
      'quickInput.background': '#050505',
      // Integrated Terminal colors
      'terminal.background': '#050505',
      'terminal.foreground': '#707080',
      'terminal.ansiBlack': '#292929',
      'terminal.ansiBlue': '#7789A3',
      'terminal.ansiBrightBlack': '#393939',
      'terminal.ansiBrightBlue': '#8799B3',
      'terminal.ansiBrightCyan': '#799A9E',
      'terminal.ansiBrightGreen': '#95A8A1',
      'terminal.ansiBrightMagenta': '#9E8AA3',
      'terminal.ansiBrightRed': '#BD9696',
      'terminal.ansiBrightWhite': '#BDBDBD',
      'terminal.ansiBrightYellow': '#C3BA9F',
      'terminal.ansiCyan': '#698A8E',
      'terminal.ansiGreen': '#859891',
      'terminal.ansiMagenta': '#8E7A93',
      'terminal.ansiRed': '#AD8686',
      'terminal.ansiWhite': '#ADADAD',
      'terminal.ansiYellow': '#B3AA8F',
      'terminal.selectionBackground': '#292929',
      'terminal.tab.activeBorder': '#00000000',
      // Git colors
      'gitDecoration.addedResourceForeground': '#81D2CEEE',
      'gitDecoration.modifiedResourceForeground': '#E7D38FBB',
      'gitDecoration.deletedResourceForeground': '#FF8787AA',
      'gitDecoration.renamedResourceForeground': '#6AB8C0BB',
      'gitDecoration.ignoredResourceForeground': '#FFFFFF3F',
      'gitDecoration.conflictingResourceForeground': '#DD9A6ABB',
      // Breadcrumbs colors
      'breadcrumb.foreground': '#666666',
    },
    tokenColors: [
      ...patcherBase(),
      ...patcherComment(),
      ...patcherGo(),
      ...patcherHTML(),
      ...patcherMarkdown(),
      ...patcherRuby(),
      ...patcherRust(),
      ...patcherVue(),
      ...patcherXML(),
      ...patcherYAML(),
    ],
    semanticHighlighting: true,
    semanticTokenColors: {
      stringLiteral: '#DD99AADD',
      customLiteral: '#EBC88DBB',
      numberLiteral: '#EBC88DBB',
    },
  }
}
